# Dr. Alex AI Demo Platform Docker Compose
version: '3.8'

services:
  demo-platform:
    build: .
    container_name: dralexai-demo
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=demo
      - PORT=4000
      - DEMO_MODE=true
    env_file:
      - .env.demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo.rule=Host(`demo.dralexai.com`)"
      - "traefik.http.routers.demo.tls=true"
      - "traefik.http.routers.demo.tls.certresolver=letsencrypt"
      - "traefik.http.services.demo.loadbalancer.server.port=4000"
    networks:
      - demo-network

networks:
  demo-network:
    external: false